// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoNX8ZZrLqC3QvZND96y3cipPd7uvoUWA',
    appId: '1:655369335313:android:1b2125b3d04b8845ae77b0',
    messagingSenderId: '655369335313',
    projectId: 'stopper-9acb4',
    databaseURL: 'https://stopper-9acb4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stopper-9acb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ5e7izo6jdlnHdiHbo5sB3LgegbYAGbI',
    appId: '1:655369335313:ios:993c40e062824a51ae77b0',
    messagingSenderId: '655369335313',
    projectId: 'stopper-9acb4',
    databaseURL: 'https://stopper-9acb4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stopper-9acb4.appspot.com',
    iosBundleId: 'com.example.stopper',
  );

}